/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fernando.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProposalCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5059370471782481699L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProposalCreatedEvent\",\"namespace\":\"com.fernando.events\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"proposalnumber\",\"type\":\"string\"},{\"name\":\"proponentdocument\",\"type\":\"string\"},{\"name\":\"product\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProposalCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProposalCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProposalCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProposalCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProposalCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProposalCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProposalCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProposalCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProposalCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence key;
  private java.lang.CharSequence proposalnumber;
  private java.lang.CharSequence proponentdocument;
  private java.lang.CharSequence product;
  private java.lang.CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProposalCreatedEvent() {}

  /**
   * All-args constructor.
   * @param key The new value for key
   * @param proposalnumber The new value for proposalnumber
   * @param proponentdocument The new value for proponentdocument
   * @param product The new value for product
   * @param status The new value for status
   */
  public ProposalCreatedEvent(java.lang.CharSequence key, java.lang.CharSequence proposalnumber, java.lang.CharSequence proponentdocument, java.lang.CharSequence product, java.lang.CharSequence status) {
    this.key = key;
    this.proposalnumber = proposalnumber;
    this.proponentdocument = proponentdocument;
    this.product = product;
    this.status = status;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    case 1: return proposalnumber;
    case 2: return proponentdocument;
    case 3: return product;
    case 4: return status;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.CharSequence)value$; break;
    case 1: proposalnumber = (java.lang.CharSequence)value$; break;
    case 2: proponentdocument = (java.lang.CharSequence)value$; break;
    case 3: product = (java.lang.CharSequence)value$; break;
    case 4: status = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'key' field.
   * @return The value of the 'key' field.
   */
  public java.lang.CharSequence getKey() {
    return key;
  }


  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.key = value;
  }

  /**
   * Gets the value of the 'proposalnumber' field.
   * @return The value of the 'proposalnumber' field.
   */
  public java.lang.CharSequence getProposalnumber() {
    return proposalnumber;
  }


  /**
   * Sets the value of the 'proposalnumber' field.
   * @param value the value to set.
   */
  public void setProposalnumber(java.lang.CharSequence value) {
    this.proposalnumber = value;
  }

  /**
   * Gets the value of the 'proponentdocument' field.
   * @return The value of the 'proponentdocument' field.
   */
  public java.lang.CharSequence getProponentdocument() {
    return proponentdocument;
  }


  /**
   * Sets the value of the 'proponentdocument' field.
   * @param value the value to set.
   */
  public void setProponentdocument(java.lang.CharSequence value) {
    this.proponentdocument = value;
  }

  /**
   * Gets the value of the 'product' field.
   * @return The value of the 'product' field.
   */
  public java.lang.CharSequence getProduct() {
    return product;
  }


  /**
   * Sets the value of the 'product' field.
   * @param value the value to set.
   */
  public void setProduct(java.lang.CharSequence value) {
    this.product = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new ProposalCreatedEvent RecordBuilder.
   * @return A new ProposalCreatedEvent RecordBuilder
   */
  public static com.fernando.events.ProposalCreatedEvent.Builder newBuilder() {
    return new com.fernando.events.ProposalCreatedEvent.Builder();
  }

  /**
   * Creates a new ProposalCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProposalCreatedEvent RecordBuilder
   */
  public static com.fernando.events.ProposalCreatedEvent.Builder newBuilder(com.fernando.events.ProposalCreatedEvent.Builder other) {
    if (other == null) {
      return new com.fernando.events.ProposalCreatedEvent.Builder();
    } else {
      return new com.fernando.events.ProposalCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProposalCreatedEvent RecordBuilder by copying an existing ProposalCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProposalCreatedEvent RecordBuilder
   */
  public static com.fernando.events.ProposalCreatedEvent.Builder newBuilder(com.fernando.events.ProposalCreatedEvent other) {
    if (other == null) {
      return new com.fernando.events.ProposalCreatedEvent.Builder();
    } else {
      return new com.fernando.events.ProposalCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProposalCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProposalCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ProposalCreatedEvent> {

    private java.lang.CharSequence key;
    private java.lang.CharSequence proposalnumber;
    private java.lang.CharSequence proponentdocument;
    private java.lang.CharSequence product;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fernando.events.ProposalCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.proposalnumber)) {
        this.proposalnumber = data().deepCopy(fields()[1].schema(), other.proposalnumber);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.proponentdocument)) {
        this.proponentdocument = data().deepCopy(fields()[2].schema(), other.proponentdocument);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.product)) {
        this.product = data().deepCopy(fields()[3].schema(), other.product);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing ProposalCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fernando.events.ProposalCreatedEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.proposalnumber)) {
        this.proposalnumber = data().deepCopy(fields()[1].schema(), other.proposalnumber);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.proponentdocument)) {
        this.proponentdocument = data().deepCopy(fields()[2].schema(), other.proponentdocument);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.product)) {
        this.product = data().deepCopy(fields()[3].schema(), other.product);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'key' field.
      * @return The value.
      */
    public java.lang.CharSequence getKey() {
      return key;
    }


    /**
      * Sets the value of the 'key' field.
      * @param value The value of 'key'.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'key' field has been set.
      * @return True if the 'key' field has been set, false otherwise.
      */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'key' field.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder clearKey() {
      key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'proposalnumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getProposalnumber() {
      return proposalnumber;
    }


    /**
      * Sets the value of the 'proposalnumber' field.
      * @param value The value of 'proposalnumber'.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder setProposalnumber(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.proposalnumber = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'proposalnumber' field has been set.
      * @return True if the 'proposalnumber' field has been set, false otherwise.
      */
    public boolean hasProposalnumber() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'proposalnumber' field.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder clearProposalnumber() {
      proposalnumber = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'proponentdocument' field.
      * @return The value.
      */
    public java.lang.CharSequence getProponentdocument() {
      return proponentdocument;
    }


    /**
      * Sets the value of the 'proponentdocument' field.
      * @param value The value of 'proponentdocument'.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder setProponentdocument(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.proponentdocument = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'proponentdocument' field has been set.
      * @return True if the 'proponentdocument' field has been set, false otherwise.
      */
    public boolean hasProponentdocument() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'proponentdocument' field.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder clearProponentdocument() {
      proponentdocument = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'product' field.
      * @return The value.
      */
    public java.lang.CharSequence getProduct() {
      return product;
    }


    /**
      * Sets the value of the 'product' field.
      * @param value The value of 'product'.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder setProduct(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.product = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'product' field has been set.
      * @return True if the 'product' field has been set, false otherwise.
      */
    public boolean hasProduct() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'product' field.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder clearProduct() {
      product = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.fernando.events.ProposalCreatedEvent.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProposalCreatedEvent build() {
      try {
        ProposalCreatedEvent record = new ProposalCreatedEvent();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.proposalnumber = fieldSetFlags()[1] ? this.proposalnumber : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.proponentdocument = fieldSetFlags()[2] ? this.proponentdocument : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.product = fieldSetFlags()[3] ? this.product : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProposalCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProposalCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProposalCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProposalCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.key);

    out.writeString(this.proposalnumber);

    out.writeString(this.proponentdocument);

    out.writeString(this.product);

    out.writeString(this.status);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.key = in.readString(this.key instanceof Utf8 ? (Utf8)this.key : null);

      this.proposalnumber = in.readString(this.proposalnumber instanceof Utf8 ? (Utf8)this.proposalnumber : null);

      this.proponentdocument = in.readString(this.proponentdocument instanceof Utf8 ? (Utf8)this.proponentdocument : null);

      this.product = in.readString(this.product instanceof Utf8 ? (Utf8)this.product : null);

      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.key = in.readString(this.key instanceof Utf8 ? (Utf8)this.key : null);
          break;

        case 1:
          this.proposalnumber = in.readString(this.proposalnumber instanceof Utf8 ? (Utf8)this.proposalnumber : null);
          break;

        case 2:
          this.proponentdocument = in.readString(this.proponentdocument instanceof Utf8 ? (Utf8)this.proponentdocument : null);
          break;

        case 3:
          this.product = in.readString(this.product instanceof Utf8 ? (Utf8)this.product : null);
          break;

        case 4:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










